### PR TITLE
Support peft models in LMI Dist

### PR DESCRIPTION
**Pull request by xyang16**
## Description ##

Brief description of what this PR is about

- If this change is a backward incompatible change, why must this change be made?
- Interesting edge cases to note here

### CODE REVIEW

**Review by lanking520 — COMMENTED** [review]
Could you add the new introduced member variable here? https://docs.djl.ai/docs/serving/serving/docs/lmi/configurations_large_model_inference_containers.html#lmi-dist Also, could we just determine wether the model is peft or not ourselves?

**Comment by xyang16** [comment]
> Could you add the new introduced member variable here? https://docs.djl.ai/docs/serving/serving/docs/lmi/configurations_large_model_inference_containers.html#lmi-dist Also, could we just determine wether the model is peft or not ourselves?

I have updated the docs. I can't find a reliable way to determine if it's peft model yet.

**Comment by siddvenk** [comment]
There might be a better way now, but we have auto detection of peft models in some of our handlers like here https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/deepspeed.py#L173.

If there is a configuration file `adapter_config.json` that we can load from PeftConfig.from_pretrained, we consider it a peft model (we assume all peft models are Lora models there)

**Comment by lanking520** [comment]
@xyang16 could we just add this simple check somewhere to check for normal model or peft model?

https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/deepspeed.py#L174-L192

**Pull request closed without merging**
