### PR TITLE
[serving] Bump up djl and serving version to 0.31.0-snapshot

### PR DESCRIPTION
**Pull request by sindhuvahinis**
## Description ##

Brief description of what this PR is about

- If this change is a backward incompatible change, why must this change be made?
- Interesting edge cases to note here

### CODE REVIEW

**Comment by frankfliu** [comment]
There are other places need to update: https://github.com/deepjavalibrary/djl-serving/pull/2416

**Comment by sindhuvahinis** [comment]
> There are other places need to update: #2416

https://github.com/deepjavalibrary/djl-serving/blob/b68b9f0a87db4d685d004243ce9097dc28566bd3/serving/docker/Dockerfile#L13 - We moved versions out of Dockerfiles.

**Comment by frankfliu** [comment]
@sindhuvahinis, see my PR: 
1. label in the dockerfile need update: https://github.com/deepjavalibrary/djl-serving/blob/master/serving/docker/lmi.Dockerfile#L135
2. onnxruntime version need change

**Comment by sindhuvahinis** [comment]
@frankfliu  Sorry, missed it. I rebased your PR against master. Closing this one.

**Pull request closed without merging**
