### PR TITLE
Add unmerged lora support in HF handler

### PR DESCRIPTION
**Pull request by rohithkrn**
## Description ##

Add unmerged lora support in HF handler. Handler expects extra `adapters` parameter to be passed to it.

E.g request: 
```
curl -X POST http://127.0.0.1:8080/invocations \
    -H "Content-Type: application/json" \
    -H "X-Amzn-SageMaker-Target-Model: base-1.tar.gz" \
    -d '{"inputs": ["How is the weather"], "adapters": ["adapter_1"], "parameters": {"max_new_tokens": 25}}'
```

Added two new functions which can be called to load and unload adapters
1. register_adapter
2. unregister_adapter

### CODE REVIEW

**Comment by siddvenk** [comment]
Are we able to support different generation parameters per adapter/request in a batch?

**Comment by rohithkrn** [comment]
> Are we able to support different generation parameters per adapter/request in a batch?

No, all adapters will need to have same generation config. For the dynamic batching case that is already enforced in the current handler.

**Comment by zachgk** [comment]
Can we add testing with this?

**Comment by rohithkrn** [comment]
> Can we add testing with this?

we don't have unit tests for handlers at this point. I wanted to add integration tests which I can do after the frontend changes are merged so that I can tests loading and unloading adapters.

**Review by zachgk — APPROVED** [review]

**Pull request merged**
